- connect-file-pulse-filters/src/main/java/io/streamthoughts/kafka/connect/filepulse/json/DefaultJSONStructConverter.java
- connect-file-pulse-filters/src/test/java/io/streamthoughts/kafka/connect/filepulse/json/DefaultJSONStructConverterTest.java
Allowing JsonFieldAccessor to read post null value element observed
> fix - continue reading post JSON null value element observed

- connect-file-pulse-api/src/main/java/io/streamthoughts/kafka/connect/filepulse/source/DelegateFileInputIterator.java
- connect-file-pulse-api/src/main/java/io/streamthoughts/kafka/connect/filepulse/source/FileObjectMeta.java
- connect-file-pulse-api/src/main/java/io/streamthoughts/kafka/connect/filepulse/source/GenericFileObjectMeta.java
- connect-file-pulse-filesystems/filepulse-amazons3-fs/pom.xml
- connect-file-pulse-filesystems/filepulse-amazons3-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/storage/aws/AmazonS3ClientConfig.java
- connect-file-pulse-filesystems/filepulse-amazons3-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/storage/aws/AmazonS3ClientUtils.java
- connect-file-pulse-filesystems/filepulse-amazons3-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/storage/aws/S3BucketKey.java
- connect-file-pulse-filesystems/filepulse-amazons3-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/storage/aws/s3/AmazonS3FileSystemListing.java
- connect-file-pulse-filesystems/filepulse-amazons3-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/storage/aws/s3/AmazonS3Storage.java
- connect-file-pulse-filesystems/filepulse-amazons3-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/storage/aws/s3/reader/AmazonS3AvroFileInputReader.java
- connect-file-pulse-filesystems/filepulse-amazons3-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/storage/aws/s3/reader/AmazonS3BytesArrayInputReader.java
- connect-file-pulse-filesystems/filepulse-amazons3-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/storage/aws/s3/reader/AmazonS3FileInputMetadataReader.java
- connect-file-pulse-filesystems/filepulse-amazons3-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/storage/aws/s3/reader/AmazonS3RowFileInputReader.java
- connect-file-pulse-filesystems/filepulse-amazons3-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/storage/aws/s3/reader/AmazonS3XMLFileInputReader.java
- connect-file-pulse-filesystems/filepulse-amazons3-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/storage/aws/s3/reader/BaseAmazonS3InputReader.java
- connect-file-pulse-filesystems/filepulse-amazons3-fs/src/test/java/io/streamthoughts/kafka/connect/filepulse/storage/aws/s3/AmazonS3FileSystemListingTest.java
- connect-file-pulse-filesystems/filepulse-amazons3-fs/src/test/java/io/streamthoughts/kafka/connect/filepulse/storage/aws/s3/BaseAmazonS3Test.java
- connect-file-pulse-filesystems/filepulse-amazons3-fs/src/test/java/io/streamthoughts/kafka/connect/filepulse/storage/aws/s3/reader/AmazonS3BytesArrayInputReaderTest.java
- connect-file-pulse-filesystems/filepulse-amazons3-fs/src/test/java/io/streamthoughts/kafka/connect/filepulse/storage/aws/s3/reader/AmazonS3RowFileInputReaderTest.java
- connect-file-pulse-filesystems/filepulse-commons-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/fs/reader/text/NonBlockingBufferReader.java
- connect-file-pulse-filesystems/filepulse-commons-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/fs/reader/text/RowFileInputIterator.java
- connect-file-pulse-filesystems/filepulse-commons-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/fs/reader/text/internal/ReversedInputFileReader.java
- connect-file-pulse-filesystems/filepulse-local-fs/src/test/java/io/streamthoughts/kafka/connect/filepulse/fs/reader/LocalRowFileInputReaderTest.java
- connect-file-pulse-plugin/pom.xml
This commit adds the new module filepulse-amazons3-fs that provides:
- AmazonS3AvroFileInputReader
- AmazonS3BytesArrayInputReader
- AmazonS3RowFileInputReader
- AmazonS3XMLFileInputReader
- AmazonS3FileSystemListing
> feat(filesystems): add support for AWS S3 (#111)

- connect-file-pulse-api/src/main/java/io/streamthoughts/kafka/connect/filepulse/source/FileObjectMeta.java
- connect-file-pulse-filesystems/filepulse-amazons3-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/storage/aws/AmazonS3ClientConfig.java
- connect-file-pulse-filesystems/filepulse-azure-blob-storage-fs/pom.xml
- connect-file-pulse-filesystems/filepulse-azure-blob-storage-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/storage/azure/AzureBlobStorageClientConfig.java
- connect-file-pulse-filesystems/filepulse-azure-blob-storage-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/storage/azure/AzureBlobStorageClientUtils.java
- connect-file-pulse-filesystems/filepulse-azure-blob-storage-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/storage/azure/blob/AzureBlobStorage.java
- connect-file-pulse-filesystems/filepulse-azure-blob-storage-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/storage/azure/blob/AzureBlobStorageFileSystemListing.java
- connect-file-pulse-filesystems/filepulse-azure-blob-storage-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/storage/azure/blob/reader/AzureBlobStorageAvroFileInputReader.java
- connect-file-pulse-filesystems/filepulse-azure-blob-storage-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/storage/azure/blob/reader/AzureBlobStorageBytesArrayInputReader.java
- connect-file-pulse-filesystems/filepulse-azure-blob-storage-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/storage/azure/blob/reader/AzureBlobStorageFileInputMetadataReader.java
- connect-file-pulse-filesystems/filepulse-azure-blob-storage-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/storage/azure/blob/reader/AzureBlobStorageInputReader.java
- connect-file-pulse-filesystems/filepulse-azure-blob-storage-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/storage/azure/blob/reader/AzureBlobStorageRowFileInputReader.java
- connect-file-pulse-filesystems/filepulse-azure-blob-storage-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/storage/azure/blob/reader/AzureBlobStorageXMLFileInputReader.java
- connect-file-pulse-filesystems/pom.xml
This commit adds the new module filepulse-azure-blob-storage-fs that provides:
- AzureBlobStorageAvroFileInputReader
- AzureBlobStorageBytesArrayInputReader
- AzureBlobStorageRowFileInputReader
- AzureBlobStorageXMLFileInputReader
- AzureBlobStorageFileSystemListing
> feat(filesystems): add support for Azure Blob Storage (#112)

- connect-file-pulse-filesystems/filepulse-commons-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/fs/reader/text/NonBlockingBufferReader.java
- connect-file-pulse-filesystems/filepulse-google-cloud-storage-fs/pom.xml
- connect-file-pulse-filesystems/filepulse-google-cloud-storage-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/storage/gcp/GcsClientConfig.java
- connect-file-pulse-filesystems/filepulse-google-cloud-storage-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/storage/gcp/GcsClientUtils.java
- connect-file-pulse-filesystems/filepulse-google-cloud-storage-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/storage/gcp/GcsFileSystemListing.java
- connect-file-pulse-filesystems/filepulse-google-cloud-storage-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/storage/gcp/GcsStorage.java
- connect-file-pulse-filesystems/filepulse-google-cloud-storage-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/storage/gcp/reader/BaseGcsInputReader.java
- connect-file-pulse-filesystems/filepulse-google-cloud-storage-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/storage/gcp/reader/GcsAvroFileInputReader.java
- connect-file-pulse-filesystems/filepulse-google-cloud-storage-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/storage/gcp/reader/GcsBytesArrayInputReader.java
- connect-file-pulse-filesystems/filepulse-google-cloud-storage-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/storage/gcp/reader/GcsFileInputMetadataReader.java
- connect-file-pulse-filesystems/filepulse-google-cloud-storage-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/storage/gcp/reader/GcsRowFileInputReader.java
- connect-file-pulse-filesystems/filepulse-google-cloud-storage-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/storage/gcp/reader/GcsXMLFileInputReader.java
- connect-file-pulse-filesystems/filepulse-google-cloud-storage-fs/src/test/java/io/streamthoughts/kafka/connect/filepulse/storage/gcp/GcsClientConfigTest.java
- connect-file-pulse-filesystems/filepulse-google-cloud-storage-fs/src/test/java/io/streamthoughts/kafka/connect/filepulse/storage/gcp/GcsStorageTest.java
- connect-file-pulse-filesystems/filepulse-google-cloud-storage-fs/src/test/java/io/streamthoughts/kafka/connect/filepulse/storage/gcp/reader/GcsRowFileInputReaderTest.java
- connect-file-pulse-filesystems/pom.xml
- connect-file-pulse-plugin/pom.xml
This commit adds classes to read object files from a GCS bucket:
- GcsStorage
- GcsFileSystemListing
- GcsAvroFileInputReader
- GcsBytesArrayInputReader
- GcsRowFileInputReader
- GcsFileInputMetadataReader
- GcsXMLFileInputReadr
Resolves: #121
> feat(filesystems): add support for Google Cloud Storage (#121)

- site/content/en/docs/Developer Guide/filters.md
Changed `format` to `formats` per:
https://github.com/streamthoughts/kafka-connect-file-pulse/blob/master/connect-file-pulse-filters/src/main/java/io/streamthoughts/kafka/connect/filepulse/config/DateFilterConfig.java
> docs(site): fix DateFilter formats config

- connect-file-pulse-expression/src/main/java/io/streamthoughts/kafka/connect/filepulse/expression/function/ExpressionFunctionExecutors.java
- connect-file-pulse-expression/src/main/java/io/streamthoughts/kafka/connect/filepulse/expression/function/strings/IsEmpty.java
- connect-file-pulse-expression/src/test/java/io/streamthoughts/kafka/connect/filepulse/expression/accessor/MapAdaptablePropertyAccessorTest.java
- connect-file-pulse-expression/src/test/java/io/streamthoughts/kafka/connect/filepulse/expression/function/strings/IsEmptyTest.java
- docs/content/en/docs/Developer Guide/accessing-data-and-metadata.md
Hello,
This adds a new SCEL expression to check if a string or an array is empty.
You could already do that with the length or equals operators, but I think having a dedicated operator for this expression will improve readability. (I have several use cases with complex expressions so this would be quite useful for us)
Best regards,
Lucas
> Add is_empty SCEL expression for string/array fields

- docs/content/en/docs/Developer Guide/handling-failures.md
The example in the documentation of Handling Error "$error.message" raise en error.
$error.exceptionMessage seems to be the correct configuration in version 2.6.0
> Fix documentation for AppendError

- pom.xml
With a recent maven version (3.8.5), the confluent dependency management failed
`
[ERROR] Failed to execute goal on project kafka-connect-filepulse-api: Could not resolve dependencies for project io.streamthoughts:kafka-connect-filepulse-api:jar:2.7.0-SNAPSHOT: Failed to collect dependencies at io.confluent:kafka-schema-registry-client:jar:6.2.1: Failed to read artifact descriptor for io.confluent:kafka-schema-registry-client:jar:6.2.1: Could not transfer artifact io.confluent:kafka-schema-registry-client:pom:6.2.1 from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [confluent (http://packages.confluent.io/maven/, default, releases+snapshots)] -> [Help 1]  
`
Recent version expect to use HTTPS in the endpoint repository
> last maven version ( > 3.8.1 ) require https repository endpoint

- connect-file-pulse-api/src/main/java/io/streamthoughts/kafka/connect/filepulse/data/Schema.java
- connect-file-pulse-api/src/main/java/io/streamthoughts/kafka/connect/filepulse/source/internal/ConnectSchemaMapper.java
- connect-file-pulse-api/src/test/java/io/streamthoughts/kafka/connect/filepulse/source/internal/ConnectSchemaMapperTest.java
- connect-file-pulse-filesystems/filepulse-google-cloud-storage-fs/pom.xml
> fix(api): fix connect schema mapping for map and array

- connect-file-pulse-filesystems/filepulse-local-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/fs/codec/GZipCodec.java
- connect-file-pulse-filesystems/filepulse-local-fs/src/test/java/io/streamthoughts/kafka/connect/filepulse/fs/LocalFSDirectoryListingTest.java
Currently pulse only decompress gz files that are created with the "application/x-gzip" MIME type. This adds support for "application/gzip" MIME type.
> fix: Add application/gzip to recognize gzipped files

- connect-file-pulse-api/src/main/java/io/streamthoughts/kafka/connect/filepulse/internal/KafkaUtils.java
- connect-file-pulse-api/src/main/java/io/streamthoughts/kafka/connect/filepulse/storage/KafkaBasedLogFactory.java
- connect-file-pulse-api/src/main/java/io/streamthoughts/kafka/connect/filepulse/storage/KafkaStateBackingStore.java
- connect-file-pulse-api/src/test/java/io/streamthoughts/kafka/connect/filepulse/internal/KafkaUtilsTest.java
- connect-file-pulse-filesystems/filepulse-amazons3-fs/pom.xml
- connect-file-pulse-plugin/src/main/java/io/streamthoughts/kafka/connect/filepulse/state/KafkaFileObjectStateBackingStore.java
- connect-file-pulse-plugin/src/main/java/io/streamthoughts/kafka/connect/filepulse/state/KafkaFileObjectStateBackingStoreConfig.java
This commit adds the aws-msk-iam-auth to enable MSK authentication. In addition, it improve KafkaStateBackingStore configuration.
Resolves: #403
> feat: Add AWS MSK IAM support

- connect-file-pulse-api/src/main/java/io/streamthoughts/kafka/connect/filepulse/storage/KafkaStateBackingStore.java
- connect-file-pulse-plugin/src/main/java/io/streamthoughts/kafka/connect/filepulse/state/KafkaFileObjectStateBackingStore.java
- connect-file-pulse-plugin/src/main/java/io/streamthoughts/kafka/connect/filepulse/state/KafkaFileObjectStateBackingStoreConfig.java
- connect-file-pulse-plugin/src/test/java/io/streamthoughts/kafka/connect/filepulse/state/KafkaFileObjectStateBackingStoreConfigTest.java
This commit adds a new boolean property to indicate if the status storage topic should be automatically created.
> feat(plugin): add tasks.file.status.storage.topic.creation.enable props

- connect-file-pulse-api/src/main/java/io/streamthoughts/kafka/connect/filepulse/data/StructSchema.java
- connect-file-pulse-filters/src/main/java/io/streamthoughts/kafka/connect/filepulse/filter/AbstractDelimitedRowFilter.java
- connect-file-pulse-filters/src/test/java/io/streamthoughts/kafka/connect/filepulse/filter/DelimitedRowFilterTest.java
DelimitedRowIndex schema has the wrong mapping of field names to index when the field names in the schema are not in alphabetical order. See `DelimitedRowFilterTest::should_use_configured_schema_when_field_names_out_of_order`
> fix(filters): fix wrong index for DelimitedRowIndex

- connect-file-pulse-api/src/main/java/io/streamthoughts/kafka/connect/filepulse/storage/StateSnapshot.java
- connect-file-pulse-plugin/src/main/java/io/streamthoughts/kafka/connect/filepulse/config/SourceConnectorConfig.java
- connect-file-pulse-plugin/src/main/java/io/streamthoughts/kafka/connect/filepulse/fs/DefaultFileSystemMonitor.java
- connect-file-pulse-plugin/src/main/java/io/streamthoughts/kafka/connect/filepulse/source/FilePulseSourceConnector.java
- connect-file-pulse-plugin/src/test/java/io/streamthoughts/kafka/connect/filepulse/MockFileSystemListing.java
- connect-file-pulse-plugin/src/test/java/io/streamthoughts/kafka/connect/filepulse/config/CommonSourceConfigTest.java
- connect-file-pulse-plugin/src/test/java/io/streamthoughts/kafka/connect/filepulse/config/SourceConnectorConfigTest.java
- connect-file-pulse-plugin/src/test/java/io/streamthoughts/kafka/connect/filepulse/config/SourceTaskConfigTest.java
> fix(plugin): fix NPE in DefaultFileSystemMonitor (#465)

- connect-file-pulse-filesystems/filepulse-amazons3-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/fs/AmazonS3FileSystemListing.java
- connect-file-pulse-filesystems/filepulse-amazons3-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/fs/AmazonS3Storage.java
Lower number of requests sent to S3 while listing objects. For buckets with large number of objects, listing can take some time, because there is a request for metadata sent to s3 for each object in the bucket. This is redundant, because all data needed for objects listing are available in S3ObjectSummary. This reduce listing time significantly.
Resolves: #490
> perf(plugin): optimize aws s3 file listing

- docker-compose.yml
The version of the file pulse image used in the docker-compose file is still the 2.13.0, it can be upgraded to 2.14.1.
There is also some reformatted lines.
> fix: upgrade file-pulse image version in docker-compose

- connect-file-pulse-filesystems/filepulse-local-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/fs/LocalFSDirectoryListing.java
- connect-file-pulse-filesystems/filepulse-local-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/fs/LocalFSDirectoryListingConfig.java
- connect-file-pulse-filesystems/filepulse-local-fs/src/test/java/io/streamthoughts/kafka/connect/filepulse/fs/LocalFSDirectoryListingTest.java
- connect-file-pulse-plugin/src/test/java/io/streamthoughts/kafka/connect/filepulse/offset/DefaultOffsetPolicyTest.java
- docs/content/en/docs/Developer Guide/file-system-listing/local-filesystem.md
feat: (plugin): Add a configuration to delete the compressed file after extraction<subject>
Add the `flag fs.delete.compress.files.enabled` indicating whether compressed file should be deleted after extraction. 
This flag is added to avoid an infinit loop when using a compressed file with the following configuration: 
"offset.attributes.string": "name+lastModified",
"fs.cleanup.policy.class": "io.streamthoughts.kafka.connect.filepulse.fs.clean.LocalMoveCleanupPolicy",
Im fact, if the compressed file is not removed, once extracted, the extracted file is processed, and move to the preconfigured folder. Therefore, the compressed file will be extrated again with a new lastModified value, and the extracted file would be processed again.
When using zipped file, is there any reason , why the …
> feat(plugin): Delete the compressed file after extraction

- docs/content/en/docs/Getting started/_index.md
- examples/connect-file-pulse-example-override-topic-and-key.json
- examples/connect-file-pulse-quickstart-avro.json
- examples/connect-file-pulse-quickstart-csv.json
- examples/connect-file-pulse-quickstart-log4j.json
- examples/connect-file-pulse-quickstart-raw.json
- examples/connect-file-pulse-quickstart-xml.json
The Kafka container used to be named "broker" and is now named "kafka".
> Align the name of the container from “broker” to “kafka”

- connect-file-pulse-filesystems/filepulse-amazons3-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/fs/AmazonS3Storage.java
The `ObjectMetadata#getStorageClass` method and the `ObjectMetadata#getETag` method may both return null. In such cases, these attributes need to be ignored to prevent a NPE issue in ConnectSchemaMapper.
> Add validation for attributes that may be null in S3 Metadata.

- connect-file-pulse-filesystems/filepulse-amazons3-fs/src/test/java/io/streamthoughts/kafka/connect/filepulse/fs/BaseBzipAmazonS3Test.java
- connect-file-pulse-filesystems/filepulse-amazons3-fs/src/test/java/io/streamthoughts/kafka/connect/filepulse/fs/BaseGzipAmazonS3Test.java
- connect-file-pulse-filesystems/filepulse-amazons3-fs/src/test/java/io/streamthoughts/kafka/connect/filepulse/fs/BaseZipAmazonS3Test.java
- connect-file-pulse-filesystems/filepulse-amazons3-fs/src/test/java/io/streamthoughts/kafka/connect/filepulse/fs/reader/AmazonS3RowBzipFileInputReaderTest.java
- connect-file-pulse-filesystems/filepulse-amazons3-fs/src/test/java/io/streamthoughts/kafka/connect/filepulse/fs/reader/AmazonS3RowGzipFileInputReaderTest.java
- connect-file-pulse-filesystems/filepulse-amazons3-fs/src/test/java/io/streamthoughts/kafka/connect/filepulse/fs/reader/AmazonS3RowZipFileInputReaderTest.java
- connect-file-pulse-filesystems/filepulse-commons-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/fs/reader/text/RowFileInputIteratorConfig.java
- connect-file-pulse-filesystems/filepulse-commons-fs/src/main/java/io/streamthoughts/kafka/connect/filepulse/fs/reader/text/RowFileInputIteratorFactory.java
`compression.method`  can be one of `zip`, `bzip`, `gzip` or blank.   This will allow reading compressed data stored on s3.
**Note:** `zip` method will only utilize the first entry
> feat(filesystems): add compression.method for zip/gzip/bzip support

- connect-file-pulse-api/src/main/java/io/streamthoughts/kafka/connect/filepulse/filter/DefaultRecordFilterPipeline.java
- connect-file-pulse-api/src/test/java/io/streamthoughts/kafka/connect/filepulse/filter/DefaultRecordFilterPipelineTest.java
> fix(filters): fix buffered records not being flushed (#667)

- connect-file-pulse-filters/src/main/java/io/streamthoughts/kafka/connect/filepulse/filter/AbstractDelimitedRowFilter.java
- connect-file-pulse-filters/src/test/java/io/streamthoughts/kafka/connect/filepulse/filter/CSVFilterTest.java
feat(filters): process the same headers but different order of columns for CSV files
Even supposed sources should be consistent. there is a scenario with same formats of CSV files but different order of header columns.  
So I implement the process for the same headers but different order of columns for CSV files.
> feat(filters): process the same headers but different order of columns for CSV files

- connect-file-pulse-plugin/src/main/java/io/streamthoughts/kafka/connect/filepulse/fs/clean/RegexRouterCleanupPolicy.java
- connect-file-pulse-plugin/src/test/java/io/streamthoughts/kafka/connect/filepulse/fs/clean/RegexRouterCleanupPolicyTest.java
Fix typo in `RegexRouterCleanupPolicy` including tests
> fix(plugin): correct regex router cleanup policy typo
